export const FETCH_STUFF = 'FETCH_STUFF';
export const RECEIVE_STUFF = 'RECEIVE_STUFF';
export const DAMAGE_HEALTH = 'DAMAGE_HEALTH';
export const EDIT_CHARACTER_INFO = 'EDIT_CHARACTER_INFO';
export const EDIT_CHARACTER_HEALTH = 'EDIT_CHARACTER_HEALTH';
export const EDIT_CHARACTER_THREATS = 'EDIT_CHARACTER_THREATS';
export const ADD_CHARACTER = 'ADD_CHARACTER';
export const SELECT_CHARACTER = 'SELECT_CHARACTER';

